// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJnDuUUFbgyYn2BvrELpC5QixwWP5sfyM',
    appId: '1:815228728421:web:16ae599793dce4eb6bc28c',
    messagingSenderId: '815228728421',
    projectId: 'social-media-83aa9',
    authDomain: 'social-media-83aa9.firebaseapp.com',
    storageBucket: 'social-media-83aa9.appspot.com',
    measurementId: 'G-37LSHRTFL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkzr0Gd3kCJiGxL1fBPip4q0EKnFfYtg',
    appId: '1:815228728421:android:fc64c5bd3548346b6bc28c',
    messagingSenderId: '815228728421',
    projectId: 'social-media-83aa9',
    storageBucket: 'social-media-83aa9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJnDuUUFbgyYn2BvrELpC5QixwWP5sfyM',
    appId: '1:815228728421:web:cb6c012385a036436bc28c',
    messagingSenderId: '815228728421',
    projectId: 'social-media-83aa9',
    authDomain: 'social-media-83aa9.firebaseapp.com',
    storageBucket: 'social-media-83aa9.appspot.com',
    measurementId: 'G-DFN3SC4439',
  );

}